<?php


/**
 * Implements hook_uninstall().
 */
function mailgun_uninstall() {
  $mail_system = variable_get('mail_system');
  $mail_system['default-system'] = 'DefaultMailSystem';
  variable_set('mail_system', $mail_system);

  variable_del('mailgun_filter_format');
  variable_del('mailgun_from');
  variable_del('mailgun_status');
  variable_del('mailgun_test_address');
  variable_del('mailgun_test_body');  
}

